package com.devpro.javaweb21Version02.dto;

public class MyConstants {

    // Replace with your email here:  
    public static final String MY_EMAIL = "cpglassesshop@gmail.com";

    // Replace password!!
    public static final String MY_PASSWORD = "pripiopgprjydjgz";

    public static final String HEADER = "<!DOCTYPE html>"
			+ "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">"
			+ "<head>"
			+ "  <meta charset=\"UTF-8\">"
			+ "  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
			+ "  <meta name=\"x-apple-disable-message-reformatting\">"
			+ "  <title></title>"
			+ "  <style>"
			+ "    table, td, div, h1, p {font-family: Arial, sans-serif;}"
			+ "  </style>"
			+ "</head>"
			+ "<body style=\"margin:0;padding:0;\">"
			+ "  <table role=\"presentation\" style=\"width:100%;border-collapse:collapse;border:0;border-spacing:0;background:#ffffff;\">"
			+ "    <tr>"
			+ "      <td align=\"center\" style=\"padding:0;\">"
			+ "        <table role=\"presentation\" style=\"width:602px;border-collapse:collapse;border:1px solid #cccccc;border-spacing:0;text-align:left;\">"
			+ "          <tr>"
			+ "            <td align=\"center\" style=\"padding:20px  0;\">"
			+ "              <img src=\"https://f10-zpcloud.zdn.vn/7017854236170937425/441fa12c0218de468709.jpg\" alt=\"\" width=\"200\" style=\"height:auto;display:block;\" />"
			+ "            </td>"
			+ "          </tr>"
			+ "          <tr>"
			+ "            <td style=\"padding:0 30px 10px 30px;\">"
			+ "              <table role=\"presentation\" style=\"width:100%;border-collapse:collapse;border:0;border-spacing:0;\">"
			+ "                <tr>"
			+ "                  <td style=\"padding:0 0 10px 0;color:#153643;\">"
			+ "                    <p style=\"margin:0 0 12px 0;font-size:16px;line-height:24px;font-family:Arial,sans-serif; font-style: italic;\">Lời đầu tiên, CP Eyes Glasses xin cảm ơn quý khách đã quan tâm đến sản phẩm, dịch vụ của cửa hàng. Chúc quý khách một ngày tốt lành.</p>"
			+ "                  </td>"
			+ "                </tr>"
			+ "                <tr>"
			+ "                  <td style=\"padding:0;\">"
			+ "                    <table role=\"presentation\" style=\"width:100%;border-collapse:collapse;border:0;border-spacing:0;\">"
			+ "                        <p style=\"margin:0 0 12px 0;font-size:16px;line-height:24px;font-family:Arial,sans-serif;\"><b>Nội dung</b>: ";

    	public static final String FOOTER = "</p>"
				+ "                    </table>"
				+ "                  </td>"
				+ "                </tr>"
				+ "              </table>"
				+ "            </td>"
				+ "          </tr>"
				+ "          <tr>"
				+ "            <td style=\"padding:30px;background:#ef7db4;\">"
				+ "              <table role=\"presentation\" style=\"width:100%;border-collapse:collapse;border:0;border-spacing:0;font-size:9px;font-family:Arial,sans-serif;\">"
				+ "                <tr>"
				+ "                  <td style=\"padding:0;width:50%;\" align=\"left\">"
				+ "                    <p style=\"margin:0;font-size:14px;line-height:16px;font-family:Arial,sans-serif;color:#ffffff;\">"
				+ "                      &reg; CP Eyes Glasses<br/>"
				+ "                    </p>"
				+ "                  </td>"
				+ "                  <td style=\"padding:0;width:50%;\" align=\"right\">"
				+ "                    <table role=\"presentation\" style=\"border-collapse:collapse;border:0;border-spacing:0;\">"
				+ "                      <tr>"
				+ "                        <td style=\"padding:0 0 0 10px;width:38px;\">"
				+ "                          <a href=\"http://www.twitter.com/\" style=\"color:#ffffff;\"><img src=\"https://assets.codepen.io/210284/tw_1.png\" alt=\"Twitter\" width=\"38\" style=\"height:auto;display:block;border:0;\" /></a>"
				+ "                        </td>"
				+ "                        <td style=\"padding:0 0 0 10px;width:38px;\">"
				+ "                          <a href=\"http://www.facebook.com/\" style=\"color:#ffffff;\"><img src=\"https://assets.codepen.io/210284/fb_1.png\" alt=\"Facebook\" width=\"38\" style=\"height:auto;display:block;border:0;\" /></a>"
				+ "                        </td>"
				+ "                      </tr>"
				+ "                    </table>"
				+ "                  </td>"
				+ "                </tr>"
				+ "              </table>"
				+ "            </td>"
				+ "          </tr>"
				+ "        </table>"
				+ "      </td>"
				+ "    </tr>"
				+ "  </table>"
				+ "</body>"
				+ "</html>";
}